name: Playwright Automation

on:
  push:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest
    
    env:
      BASE_URL: ${{ secrets.BASE_URL}}
      EMAIL: ${{ secrets.EMAIL}}
      PASSWORD: ${{ secrets.PASSWORD}}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install Dependencies
      working-directory: Playwright
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright Browsers
      working-directory: Playwright
      run: playwright install
      
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.34.1.tgz
        tar -zxvf allure-2.34.1.tgz
        sudo mv allure-2.34.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
    
    - name: Run Playwright Automation
      working-directory: Playwright
      run: make allure-ci
    
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: Playwright/allure-results

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: Playwright/allure-report
